## Installation for pytorch (new Version: 2.1.2 currently)
%pip install -U --user torch torchvision torchaudio 
%pip install -U numpy --user
%pip install -U panda --user
import sys
sys.path.append("/home/j7zang/.local/lib/python3.10/site-packages")

!nvidia-msi

### Start Codding Here: 

In [7]:
import torch   
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
print(torch.__version__)

1.12.1


In [9]:
scalar = torch.tensor(7)
scalar.item()
vector = torch.tensor([2,2])
vector.ndim
vector.shape
MATRIX = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
MATRIX.ndim
MATRIX.shape

torch.Size([1, 3, 3])

In [10]:
randon_tensor = torch.rand(size=(48,48,1),device="cpu")
randon_tensor.shape

torch.Size([48, 48, 1])

In [11]:
randon_tensor.dtype

torch.float32

In [12]:
ones_tensor = torch.ones(size=(48,48,1),dtype=torch.half)
ones_tensor.dtype

torch.float16

In [13]:
zeros_tensor = torch.zeros_like(input=randon_tensor)
zeros_tensor.shape, zeros_tensor.device, zeros_tensor.dtype

(torch.Size([48, 48, 1]), device(type='cpu'), torch.float32)

In [14]:
list_tensor = torch.arange(1,101,10)
list_tensor, list_tensor.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [15]:
randon_tensorA = torch.rand(2,3)
randon_tensorB = randon_tensorA
torch.mm(randon_tensorA, randon_tensorB.T)

tensor([[1.5013, 0.8429],
        [0.8429, 0.5915]])

In [16]:
randon_tensorA,randon_tensorA.max(),randon_tensorA.min()

(tensor([[0.8963, 0.4425, 0.7087],
         [0.5170, 0.5318, 0.2035]]),
 tensor(0.8963),
 tensor(0.2035))

In [17]:
list_tensor.type(torch.float32).mean(), list_tensor.type(torch.float32).median()

(tensor(46.), tensor(41.))

In [31]:
image_tensor = torch.rand(345,345,3)
image_tensor.shape

torch.Size([345, 345, 3])

In [30]:
image_tensor.reshape(115,115,27).shape

torch.Size([115, 115, 27])

In [66]:
different_view = image_tensor.view(115,115,27)
different_view[0,0,0] = 9 # just a pointer will shange original matrix same
image_tensor

tensor([[[9.0000e+00, 9.5114e-02, 1.8963e-02],
         [4.8922e-01, 5.0565e-01, 6.2698e-01],
         [3.4313e-01, 2.6177e-01, 2.4234e-01],
         ...,
         [3.4801e-01, 8.9002e-01, 7.8791e-01],
         [2.3174e-01, 3.6311e-01, 4.3433e-01],
         [3.6376e-01, 3.7134e-01, 8.3908e-01]],

        [[3.8710e-01, 2.8872e-02, 4.4529e-01],
         [5.2987e-03, 6.3932e-01, 5.5212e-01],
         [3.5481e-01, 3.7149e-01, 2.2187e-01],
         ...,
         [7.0491e-01, 1.4186e-01, 3.9130e-01],
         [6.5829e-01, 3.0551e-01, 3.9572e-01],
         [1.3164e-01, 1.6737e-01, 6.0167e-01]],

        [[7.6266e-01, 1.6542e-02, 4.1568e-01],
         [1.3579e-01, 1.7777e-01, 7.2644e-01],
         [2.0493e-01, 9.4290e-01, 6.9076e-01],
         ...,
         [2.5215e-01, 9.0408e-01, 6.8937e-01],
         [2.0162e-01, 3.8405e-01, 9.5638e-01],
         [4.9810e-01, 5.8537e-01, 9.0289e-01]],

        ...,

        [[6.4337e-01, 8.2087e-01, 7.9775e-01],
         [8.5822e-01, 4.3240e-01, 9.0340e-01]

In [24]:
test_tensor = torch.zeros(1,2,1,2,2)
torch.squeeze(test_tensor,0).shape

torch.Size([2, 1, 2, 2])

In [26]:
torch.unsqueeze(test_tensor,5).shape

torch.Size([1, 2, 1, 2, 2, 1])

In [61]:
torch.stack([test_tensor,test_tensor,test_tensor],dim=0).shape, torch.stack([test_tensor,test_tensor,test_tensor],dim=1).shape

(torch.Size([3, 1, 2, 1, 2, 2]), torch.Size([1, 3, 2, 1, 2, 2]))

In [53]:
test_tensor.shape

torch.Size([1, 2, 1, 2, 2])

In [52]:
torch.vstack([test_tensor,test_tensor,test_tensor]).shape

torch.Size([3, 2, 1, 2, 2])

In [62]:
torch.hstack([test_tensor,test_tensor,test_tensor]).shape

torch.Size([1, 6, 1, 2, 2])

In [67]:
torch.permute(image_tensor,(2,0,1))

tensor([[[9.0000e+00, 4.8922e-01, 3.4313e-01,  ..., 3.4801e-01,
          2.3174e-01, 3.6376e-01],
         [3.8710e-01, 5.2987e-03, 3.5481e-01,  ..., 7.0491e-01,
          6.5829e-01, 1.3164e-01],
         [7.6266e-01, 1.3579e-01, 2.0493e-01,  ..., 2.5215e-01,
          2.0162e-01, 4.9810e-01],
         ...,
         [6.4337e-01, 8.5822e-01, 5.8943e-01,  ..., 4.9908e-01,
          7.4822e-01, 9.5127e-01],
         [4.5530e-01, 1.2545e-01, 8.8197e-01,  ..., 4.1109e-01,
          9.2612e-01, 1.4327e-01],
         [4.6124e-01, 9.8334e-01, 8.2550e-01,  ..., 2.8490e-01,
          1.9583e-01, 6.5040e-01]],

        [[9.5114e-02, 5.0565e-01, 2.6177e-01,  ..., 8.9002e-01,
          3.6311e-01, 3.7134e-01],
         [2.8872e-02, 6.3932e-01, 3.7149e-01,  ..., 1.4186e-01,
          3.0551e-01, 1.6737e-01],
         [1.6542e-02, 1.7777e-01, 9.4290e-01,  ..., 9.0408e-01,
          3.8405e-01, 5.8537e-01],
         ...,
         [8.2087e-01, 4.3240e-01, 6.9626e-01,  ..., 6.3798e-01,
          5.633