## Installation for pytorch
!pip3 install torch torchvision torchaudio --user
!pip3 install numpy --user
!pip3 install panda --user

!nvidia-msi

### Start Codding Here: 

In [2]:
import torch   
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
scalar = torch.tensor(7)
scalar.item()
vector = torch.tensor([2,2])
vector.ndim
vector.shape
MATRIX = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
MATRIX.ndim
MATRIX.shape

torch.Size([1, 3, 3])

In [4]:
randon_tensor = torch.rand(size=(48,48,1),device="cpu")
randon_tensor.shape

torch.Size([48, 48, 1])

In [5]:
randon_tensor.dtype

torch.float32

In [6]:
ones_tensor = torch.ones(size=(48,48,1),dtype=torch.half)
ones_tensor.dtype

torch.float16

In [7]:
zeros_tensor = torch.zeros_like(input=randon_tensor)
zeros_tensor.shape, zeros_tensor.device, zeros_tensor.dtype

(torch.Size([48, 48, 1]), device(type='cpu'), torch.float32)

In [8]:
list_tensor = torch.arange(1,101,10)
list_tensor, list_tensor.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [9]:
randon_tensorA = torch.rand(2,3)
randon_tensorB = randon_tensorA
torch.mm(randon_tensorA, randon_tensorB.T)

tensor([[0.1344, 0.0866],
        [0.0866, 0.5470]])

In [10]:
randon_tensorA,randon_tensorA.max(),randon_tensorA.min()

(tensor([[0.3512, 0.0286, 0.1008],
         [0.0418, 0.4501, 0.5854]]),
 tensor(0.5854),
 tensor(0.0286))

In [11]:
list_tensor.type(torch.float32).mean(), list_tensor.type(torch.float32).median()

(tensor(46.), tensor(41.))

In [13]:
image_tensor = torch.rand(345,345,3)
image_tensor

tensor([[[0.5215, 0.3599, 0.1717],
         [0.9125, 0.1629, 0.6371],
         [0.3208, 0.0521, 0.7520],
         ...,
         [0.1161, 0.6086, 0.9188],
         [0.8401, 0.0129, 0.3257],
         [0.2110, 0.4795, 0.2676]],

        [[0.8068, 0.2659, 0.6625],
         [0.0567, 0.9979, 0.6300],
         [0.7643, 0.1929, 0.7453],
         ...,
         [0.5998, 0.9364, 0.8945],
         [0.8604, 0.3967, 0.2627],
         [0.6636, 0.0521, 0.2332]],

        [[0.4274, 0.3702, 0.4069],
         [0.7514, 0.2719, 0.8350],
         [0.4606, 0.5819, 0.2436],
         ...,
         [0.7712, 0.0789, 0.4022],
         [0.6569, 0.0669, 0.0580],
         [0.7180, 0.9225, 0.9958]],

        ...,

        [[0.4244, 0.0131, 0.5382],
         [0.1408, 0.4093, 0.7369],
         [0.8250, 0.4468, 0.4401],
         ...,
         [0.4103, 0.9239, 0.8236],
         [0.8483, 0.0544, 0.0282],
         [0.9491, 0.0832, 0.7701]],

        [[0.7606, 0.5606, 0.8124],
         [0.4368, 0.4031, 0.2249],
         [0.

In [16]:
image_tensor.reshape(115,115,27)

tensor([[[0.5215, 0.3599, 0.1717,  ..., 0.4746, 0.1369, 0.0897],
         [0.8137, 0.0302, 0.1241,  ..., 0.3739, 0.3434, 0.3785],
         [0.9496, 0.8106, 0.7806,  ..., 0.3665, 0.7625, 0.5386],
         ...,
         [0.3385, 0.8808, 0.7398,  ..., 0.3792, 0.8035, 0.7872],
         [0.1505, 0.8247, 0.2135,  ..., 0.4403, 0.7103, 0.9962],
         [0.8728, 0.0406, 0.4148,  ..., 0.7180, 0.9225, 0.9958]],

        [[0.2358, 0.5102, 0.9383,  ..., 0.4387, 0.6815, 0.7307],
         [0.6133, 0.7425, 0.7517,  ..., 0.2308, 0.7667, 0.9488],
         [0.0018, 0.0227, 0.4490,  ..., 0.9231, 0.4390, 0.3170],
         ...,
         [0.1057, 0.8094, 0.0091,  ..., 0.7111, 0.8820, 0.8421],
         [0.2335, 0.7004, 0.4721,  ..., 0.7368, 0.4550, 0.9180],
         [0.4752, 0.9553, 0.9221,  ..., 0.7063, 0.7722, 0.2490]],

        [[0.0495, 0.7499, 0.4031,  ..., 0.6775, 0.9257, 0.6854],
         [0.4809, 0.6616, 0.4189,  ..., 0.1438, 0.5511, 0.1267],
         [0.4925, 0.8348, 0.6266,  ..., 0.7062, 0.5138, 0.

In [20]:
different_view = image_tensor.view(115,115,27)
different_view[0,0,0] = 9
image_tensor, different_view

(tensor([[[9.0000, 0.3599, 0.1717],
          [0.9125, 0.1629, 0.6371],
          [0.3208, 0.0521, 0.7520],
          ...,
          [0.1161, 0.6086, 0.9188],
          [0.8401, 0.0129, 0.3257],
          [0.2110, 0.4795, 0.2676]],
 
         [[0.8068, 0.2659, 0.6625],
          [0.0567, 0.9979, 0.6300],
          [0.7643, 0.1929, 0.7453],
          ...,
          [0.5998, 0.9364, 0.8945],
          [0.8604, 0.3967, 0.2627],
          [0.6636, 0.0521, 0.2332]],
 
         [[0.4274, 0.3702, 0.4069],
          [0.7514, 0.2719, 0.8350],
          [0.4606, 0.5819, 0.2436],
          ...,
          [0.7712, 0.0789, 0.4022],
          [0.6569, 0.0669, 0.0580],
          [0.7180, 0.9225, 0.9958]],
 
         ...,
 
         [[0.4244, 0.0131, 0.5382],
          [0.1408, 0.4093, 0.7369],
          [0.8250, 0.4468, 0.4401],
          ...,
          [0.4103, 0.9239, 0.8236],
          [0.8483, 0.0544, 0.0282],
          [0.9491, 0.0832, 0.7701]],
 
         [[0.7606, 0.5606, 0.8124],
          [0

In [23]:
image_tensor.squeeze(0)

tensor([[[9.0000, 0.3599, 0.1717],
         [0.9125, 0.1629, 0.6371],
         [0.3208, 0.0521, 0.7520],
         ...,
         [0.1161, 0.6086, 0.9188],
         [0.8401, 0.0129, 0.3257],
         [0.2110, 0.4795, 0.2676]],

        [[0.8068, 0.2659, 0.6625],
         [0.0567, 0.9979, 0.6300],
         [0.7643, 0.1929, 0.7453],
         ...,
         [0.5998, 0.9364, 0.8945],
         [0.8604, 0.3967, 0.2627],
         [0.6636, 0.0521, 0.2332]],

        [[0.4274, 0.3702, 0.4069],
         [0.7514, 0.2719, 0.8350],
         [0.4606, 0.5819, 0.2436],
         ...,
         [0.7712, 0.0789, 0.4022],
         [0.6569, 0.0669, 0.0580],
         [0.7180, 0.9225, 0.9958]],

        ...,

        [[0.4244, 0.0131, 0.5382],
         [0.1408, 0.4093, 0.7369],
         [0.8250, 0.4468, 0.4401],
         ...,
         [0.4103, 0.9239, 0.8236],
         [0.8483, 0.0544, 0.0282],
         [0.9491, 0.0832, 0.7701]],

        [[0.7606, 0.5606, 0.8124],
         [0.4368, 0.4031, 0.2249],
         [0.

In [24]:
image_tensor.squeeze(1)

tensor([[[9.0000, 0.3599, 0.1717],
         [0.9125, 0.1629, 0.6371],
         [0.3208, 0.0521, 0.7520],
         ...,
         [0.1161, 0.6086, 0.9188],
         [0.8401, 0.0129, 0.3257],
         [0.2110, 0.4795, 0.2676]],

        [[0.8068, 0.2659, 0.6625],
         [0.0567, 0.9979, 0.6300],
         [0.7643, 0.1929, 0.7453],
         ...,
         [0.5998, 0.9364, 0.8945],
         [0.8604, 0.3967, 0.2627],
         [0.6636, 0.0521, 0.2332]],

        [[0.4274, 0.3702, 0.4069],
         [0.7514, 0.2719, 0.8350],
         [0.4606, 0.5819, 0.2436],
         ...,
         [0.7712, 0.0789, 0.4022],
         [0.6569, 0.0669, 0.0580],
         [0.7180, 0.9225, 0.9958]],

        ...,

        [[0.4244, 0.0131, 0.5382],
         [0.1408, 0.4093, 0.7369],
         [0.8250, 0.4468, 0.4401],
         ...,
         [0.4103, 0.9239, 0.8236],
         [0.8483, 0.0544, 0.0282],
         [0.9491, 0.0832, 0.7701]],

        [[0.7606, 0.5606, 0.8124],
         [0.4368, 0.4031, 0.2249],
         [0.