## Installation for pytorch
!pip3 install torch torchvision torchaudio --user
!pip3 install numpy --user
!pip3 install panda --user

!nvidia-msi

### Start Codding Here: 

In [2]:
import torch   
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
scalar = torch.tensor(7)
scalar.item()
vector = torch.tensor([2,2])
vector.ndim
vector.shape
MATRIX = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
MATRIX.ndim
MATRIX.shape

torch.Size([1, 3, 3])

In [4]:
randon_tensor = torch.rand(size=(48,48,1),device="cpu")
randon_tensor.shape

torch.Size([48, 48, 1])

In [5]:
randon_tensor.dtype

torch.float32

In [6]:
ones_tensor = torch.ones(size=(48,48,1),dtype=torch.half)
ones_tensor.dtype

torch.float16

In [8]:
zeros_tensor = torch.zeros_like(input=randon_tensor)
zeros_tensor.shape, zeros_tensor.device, zeros_tensor.dtype

(torch.Size([48, 48, 1]), device(type='cpu'), torch.float32)

In [27]:
list_tensor = torch.arange(1,101,10)
list_tensor, list_tensor.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [14]:
randon_tensorA = torch.rand(2,3)
randon_tensorB = randon_tensorA
torch.mm(randon_tensorA, randon_tensorB.T)

tensor([[1.1917, 0.9688],
        [0.9688, 0.9457]])

In [19]:
randon_tensorA,randon_tensorA.max(),randon_tensorA.min()

(tensor([[0.3966, 0.5802, 0.8353],
         [0.3535, 0.7902, 0.4431]]),
 tensor(0.8353),
 tensor(0.3535))

In [26]:
list_tensor.type(torch.float32).mean(), list_tensor.type(torch.float32).median()

(tensor(46.), tensor(41.))