## Installation for pytorch (new Version: 2.1.2 currently)
%pip install -U --user torch torchvision torchaudio 
%pip install -U numpy --user
%pip install -U panda --user
import sys
sys.path.append("/home/j7zang/.local/lib/python3.10/site-packages")

!nvidia-msi

### Start Codding Here: 

In [1]:
import torch   
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

1.12.1


In [3]:
scalar = torch.tensor(7)
scalar.item()
vector = torch.tensor([2,2])
vector.ndim
vector.shape
MATRIX = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
MATRIX.ndim
MATRIX.shape

torch.Size([1, 3, 3])

In [4]:
randon_tensor = torch.rand(size=(48,48,1),device="cpu")
randon_tensor.shape

torch.Size([48, 48, 1])

In [5]:
randon_tensor.dtype

torch.float32

In [6]:
ones_tensor = torch.ones(size=(48,48,1),dtype=torch.half)
ones_tensor.dtype

torch.float16

In [7]:
zeros_tensor = torch.zeros_like(input=randon_tensor)
zeros_tensor.shape, zeros_tensor.device, zeros_tensor.dtype

(torch.Size([48, 48, 1]), device(type='cpu'), torch.float32)

In [8]:
list_tensor = torch.arange(1,101,10)
list_tensor, list_tensor.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [9]:
randon_tensorA = torch.rand(2,3)
randon_tensorB = randon_tensorA
torch.mm(randon_tensorA, randon_tensorB.T)

tensor([[0.8894, 0.9364],
        [0.9364, 1.2191]])

In [10]:
randon_tensorA,randon_tensorA.max(),randon_tensorA.min()

(tensor([[0.4885, 0.7927, 0.1492],
         [0.5817, 0.7064, 0.6178]]),
 tensor(0.7927),
 tensor(0.1492))

In [11]:
list_tensor.type(torch.float32).mean(), list_tensor.type(torch.float32).median()

(tensor(46.), tensor(41.))

In [12]:
image_tensor = torch.rand(345,345,3)
image_tensor.shape

torch.Size([345, 345, 3])

In [13]:
image_tensor.reshape(115,115,27).shape

torch.Size([115, 115, 27])

In [14]:
different_view = image_tensor.view(115,115,27)
different_view[0,0,0] = 9 # just a pointer will shange original matrix same
image_tensor

tensor([[[9.0000, 0.4055, 0.8307],
         [0.6722, 0.2045, 0.0500],
         [0.0656, 0.0758, 0.0360],
         ...,
         [0.8651, 0.8146, 0.5787],
         [0.1267, 0.3484, 0.3236],
         [0.8303, 0.7465, 0.3380]],

        [[0.9985, 0.1503, 0.8764],
         [0.6972, 0.2069, 0.9792],
         [0.7109, 0.8641, 0.9124],
         ...,
         [0.5601, 0.7299, 0.2166],
         [0.2046, 0.9793, 0.2517],
         [0.1895, 0.8127, 0.6153]],

        [[0.2669, 0.8384, 0.9986],
         [0.0661, 0.6477, 0.3489],
         [0.4042, 0.7599, 0.6569],
         ...,
         [0.4240, 0.3415, 0.1390],
         [0.8165, 0.2461, 0.0368],
         [0.7697, 0.3144, 0.5777]],

        ...,

        [[0.8412, 0.8074, 0.2820],
         [0.4531, 0.7143, 0.1059],
         [0.2150, 0.4902, 0.0556],
         ...,
         [0.3426, 0.9286, 0.8720],
         [0.1960, 0.9735, 0.0130],
         [0.3360, 0.8997, 0.3695]],

        [[0.3113, 0.2920, 0.9192],
         [0.1356, 0.2210, 0.7104],
         [0.

In [15]:
test_tensor = torch.zeros(1,2,1,2,2)
torch.squeeze(test_tensor,0).shape

torch.Size([2, 1, 2, 2])

In [16]:
torch.unsqueeze(test_tensor,5).shape

torch.Size([1, 2, 1, 2, 2, 1])

In [17]:
torch.stack([test_tensor,test_tensor,test_tensor],dim=0).shape, torch.stack([test_tensor,test_tensor,test_tensor],dim=1).shape

(torch.Size([3, 1, 2, 1, 2, 2]), torch.Size([1, 3, 2, 1, 2, 2]))

In [18]:
test_tensor.shape

torch.Size([1, 2, 1, 2, 2])

In [19]:
torch.vstack([test_tensor,test_tensor,test_tensor]).shape

torch.Size([3, 2, 1, 2, 2])

In [20]:
torch.hstack([test_tensor,test_tensor,test_tensor]).shape

torch.Size([1, 6, 1, 2, 2])

In [23]:
torch.permute(image_tensor,(2,0,1))

tensor([[[9.0000, 0.6722, 0.0656,  ..., 0.8651, 0.1267, 0.8303],
         [0.9985, 0.6972, 0.7109,  ..., 0.5601, 0.2046, 0.1895],
         [0.2669, 0.0661, 0.4042,  ..., 0.4240, 0.8165, 0.7697],
         ...,
         [0.8412, 0.4531, 0.2150,  ..., 0.3426, 0.1960, 0.3360],
         [0.3113, 0.1356, 0.0479,  ..., 0.5795, 0.4870, 0.0735],
         [0.2372, 0.7161, 0.3652,  ..., 0.7935, 0.5458, 0.1447]],

        [[0.4055, 0.2045, 0.0758,  ..., 0.8146, 0.3484, 0.7465],
         [0.1503, 0.2069, 0.8641,  ..., 0.7299, 0.9793, 0.8127],
         [0.8384, 0.6477, 0.7599,  ..., 0.3415, 0.2461, 0.3144],
         ...,
         [0.8074, 0.7143, 0.4902,  ..., 0.9286, 0.9735, 0.8997],
         [0.2920, 0.2210, 0.2826,  ..., 0.5424, 0.3872, 0.0105],
         [0.7310, 0.7369, 0.1333,  ..., 0.3224, 0.6028, 0.1605]],

        [[0.8307, 0.0500, 0.0360,  ..., 0.5787, 0.3236, 0.3380],
         [0.8764, 0.9792, 0.9124,  ..., 0.2166, 0.2517, 0.6153],
         [0.9986, 0.3489, 0.6569,  ..., 0.1390, 0.0368, 0.

In [29]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [30]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [46]:
x[0,0]

tensor([1, 2, 3])

In [48]:
x[:,2,:]

tensor([[7, 8, 9]])

In [49]:
x[:,:,1]

tensor([[2, 5, 8]])

In [35]:
import numpy as np

In [38]:
np_example = np.arange(0,10)
np_example

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
trans_torch = torch.from_numpy(np_example)
trans_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
trans_torch.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])