## Installation for pytorch (new Version: 2.1.2 currently)
%pip install -U --user torch torchvision torchaudio 
%pip install -U numpy --user
%pip install -U panda --user
import sys
sys.path.append("/home/j7zang/.local/lib/python3.10/site-packages")

In [89]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### Start Codding Here: 

In [90]:
import torch   
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [91]:
print(torch.__version__)

1.12.1


In [92]:
scalar = torch.tensor(7)
scalar.item()
vector = torch.tensor([2,2])
vector.ndim
vector.shape
MATRIX = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
MATRIX.ndim
MATRIX.shape

torch.Size([1, 3, 3])

In [93]:
randon_tensor = torch.rand(size=(48,48,1),device="cpu")
randon_tensor.shape

torch.Size([48, 48, 1])

In [94]:
randon_tensor.dtype

torch.float32

In [95]:
ones_tensor = torch.ones(size=(48,48,1),dtype=torch.half)
ones_tensor.dtype

torch.float16

In [96]:
zeros_tensor = torch.zeros_like(input=randon_tensor)
zeros_tensor.shape, zeros_tensor.device, zeros_tensor.dtype

(torch.Size([48, 48, 1]), device(type='cpu'), torch.float32)

In [97]:
list_tensor = torch.arange(1,101,10)
list_tensor, list_tensor.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [98]:
randon_tensorA = torch.rand(2,3)
randon_tensorB = randon_tensorA
torch.mm(randon_tensorA, randon_tensorB.T)

tensor([[0.3000, 0.2283],
        [0.2283, 0.2697]])

In [99]:
randon_tensorA,randon_tensorA.max(),randon_tensorA.min()

(tensor([[0.1919, 0.1603, 0.4873],
         [0.0423, 0.4091, 0.3172]]),
 tensor(0.4873),
 tensor(0.0423))

In [100]:
list_tensor.type(torch.float32).mean(), list_tensor.type(torch.float32).median()

(tensor(46.), tensor(41.))

In [101]:
image_tensor = torch.rand(345,345,3)
image_tensor.shape

torch.Size([345, 345, 3])

In [102]:
image_tensor.reshape(115,115,27).shape

torch.Size([115, 115, 27])

In [103]:
different_view = image_tensor.view(115,115,27)
different_view[0,0,0] = 9 # just a pointer will shange original matrix same
image_tensor

tensor([[[9.0000, 0.9064, 0.7904],
         [0.5280, 0.3381, 0.6275],
         [0.1545, 0.2867, 0.3996],
         ...,
         [0.2478, 0.2675, 0.9979],
         [0.5962, 0.7153, 0.5672],
         [0.1629, 0.8608, 0.4223]],

        [[0.3705, 0.9075, 0.2453],
         [0.6015, 0.0747, 0.7562],
         [0.6986, 0.0889, 0.7791],
         ...,
         [0.8020, 0.7075, 0.0482],
         [0.4728, 0.2848, 0.4133],
         [0.7784, 0.4462, 0.1527]],

        [[0.8517, 0.0430, 0.3283],
         [0.6927, 0.9419, 0.9853],
         [0.3825, 0.6668, 0.0609],
         ...,
         [0.0870, 0.5017, 0.9243],
         [0.1908, 0.5979, 0.1554],
         [0.1125, 0.3162, 0.1653]],

        ...,

        [[0.1352, 0.7747, 0.2024],
         [0.9197, 0.0984, 0.2042],
         [0.7761, 0.9115, 0.2869],
         ...,
         [0.8225, 0.9508, 0.9409],
         [0.6034, 0.8677, 0.4384],
         [0.2543, 0.5465, 0.9475]],

        [[0.5892, 0.5733, 0.8606],
         [0.0306, 0.2301, 0.4313],
         [0.

In [104]:
test_tensor = torch.zeros(1,2,1,2,2)
torch.squeeze(test_tensor,0).shape

torch.Size([2, 1, 2, 2])

In [105]:
torch.unsqueeze(test_tensor,5).shape

torch.Size([1, 2, 1, 2, 2, 1])

In [106]:
torch.stack([test_tensor,test_tensor,test_tensor],dim=0).shape, torch.stack([test_tensor,test_tensor,test_tensor],dim=1).shape

(torch.Size([3, 1, 2, 1, 2, 2]), torch.Size([1, 3, 2, 1, 2, 2]))

In [107]:
test_tensor.shape

torch.Size([1, 2, 1, 2, 2])

In [108]:
torch.vstack([test_tensor,test_tensor,test_tensor]).shape

torch.Size([3, 2, 1, 2, 2])

In [109]:
torch.hstack([test_tensor,test_tensor,test_tensor]).shape

torch.Size([1, 6, 1, 2, 2])

In [110]:
torch.permute(image_tensor,(2,0,1))

tensor([[[9.0000, 0.5280, 0.1545,  ..., 0.2478, 0.5962, 0.1629],
         [0.3705, 0.6015, 0.6986,  ..., 0.8020, 0.4728, 0.7784],
         [0.8517, 0.6927, 0.3825,  ..., 0.0870, 0.1908, 0.1125],
         ...,
         [0.1352, 0.9197, 0.7761,  ..., 0.8225, 0.6034, 0.2543],
         [0.5892, 0.0306, 0.6216,  ..., 0.0348, 0.1063, 0.3399],
         [0.5667, 0.0709, 0.0496,  ..., 0.0893, 0.2728, 0.2659]],

        [[0.9064, 0.3381, 0.2867,  ..., 0.2675, 0.7153, 0.8608],
         [0.9075, 0.0747, 0.0889,  ..., 0.7075, 0.2848, 0.4462],
         [0.0430, 0.9419, 0.6668,  ..., 0.5017, 0.5979, 0.3162],
         ...,
         [0.7747, 0.0984, 0.9115,  ..., 0.9508, 0.8677, 0.5465],
         [0.5733, 0.2301, 0.1227,  ..., 0.8204, 0.6874, 0.1653],
         [0.9937, 0.0657, 0.0928,  ..., 0.4143, 0.2818, 0.9138]],

        [[0.7904, 0.6275, 0.3996,  ..., 0.9979, 0.5672, 0.4223],
         [0.2453, 0.7562, 0.7791,  ..., 0.0482, 0.4133, 0.1527],
         [0.3283, 0.9853, 0.0609,  ..., 0.9243, 0.1554, 0.

In [111]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [112]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [113]:
x[0,0]

tensor([1, 2, 3])

In [114]:
x[:,2,:]

tensor([[7, 8, 9]])

In [115]:
x[:,:,1]

tensor([[2, 5, 8]])

In [116]:
import numpy as np

In [117]:
np_example = np.arange(0,10)
np_example

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
trans_torch = torch.from_numpy(np_example)
trans_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
trans_torch.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A == random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [121]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [122]:
torch.cuda.is_available()

False

In [130]:
torch.cuda.device_count()
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [143]:
tensor = torch.tensor([1,2,3])
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [141]:
#If tensor is on GPU, can't transform it to NumpPy
#tensor_on_gpu.numpy()
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])